name: Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: skysense/data-tools-image/data-tools-image
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
